steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/vider-backend', '-f', 'server/Dockerfile', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vider-backend']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vider-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vider-backend'
      - '--region'
      - 'europe-north1' # Oslo region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--quiet'
      - '--add-cloudsql-instances'
      - '${_CLOUD_SQL_CONNECTION_NAME}'
      - '--set-env-vars'
      - 'DATABASE_URL=${_DATABASE_URL},NODE_ENV=production'

images:
  - 'gcr.io/$PROJECT_ID/vider-backend'

substitutions:
  _CLOUD_SQL_CONNECTION_NAME: 'your-project:region:instance'
  _DATABASE_URL: 'postgresql://user:password@localhost/dbname?host=/cloudsql/your-project:region:instance'
