/**
 * Property-Based Test: Role-Based Form Validation
 * **Feature: company-user-creation, Property 4: Role-Based Form Validation**
 * **Validates: Requirements 2.2, 2.3**
 * 
 * Tests that role-based validation works correctly for different user roles
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { PrismaClient } from '@prisma/client';
import fc from 'fast-check';

const prisma = new PrismaClient();

// Test data setup
let testCompany: any;

beforeAll(async () => {
  // Create a test company
  testCompany = await prisma.company.create({
    data: {
      name: 'Test Company for Role Validation',
      organizationNumber: `TEST${Date.now()}`,
      businessAddress: 'Test Business Address',
      city: 'Oslo',
      postalCode: '0001',
      fylke: 'Oslo',
      kommune: 'Oslo',
      vatRegistered: true,
      description: 'Test company for role validation',
      verified: true,
      verifiedAt: new Date(),
      aggregatedRating: 4.0,
      totalRatings: 1,
      status: 'ACTIVE'
    }
  });

  // Create admin user and get token
  const adminUser = await prisma.user.create({
    data: {
      email: `admin-role-validation-${Date.now()}@example.com`,
      firstName: 'Admin',
      lastName: 'User',
      phone: '+47 12345678',
      role: 'PLATFORM_ADMIN',
      passwordHash: 'dummy-hash',
      emailVerified: true,
      company: {
        connect: { id: testCompany.id }
      }
    }
  });

  // Mock admin token (in real app, this would be generated by auth system)
  adminToken = 'mock-admin-token';
});

afterAll(async () => {
  // Clean up test data
  await prisma.user.deleteMany({
    where: {
      OR: [
        { email: { contains: 'role-validation-test' } },
        { email: { contains: 'admin-role-validation' } }
      ]
    }
  });

  await prisma.company.deleteMany({
    where: {
      name: 'Test Company for Role Validation'
    }
  });

  await prisma.$disconnect();
});

describe('Property 4: Role-Based Form Validation', () => {
  it.skip('should require permissions for COMPANY_ADMIN role', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.record({
          email: fc.emailAddress(),
          firstName: fc.string({ minLength: 1, maxLength: 50 }),
          lastName: fc.string({ minLength: 1, maxLength: 50 }),
          phone: fc.option(fc.string({ minLength: 8, maxLength: 15 }), { nil: undefined }),
          role: fc.constant('COMPANY_ADMIN'),
          companyId: fc.constant(testCompany.id),
          permissions: fc.option(fc.array(fc.constantFrom('MANAGE_DRIVERS', 'VIEW_BOOKINGS', 'MANAGE_VEHICLES')), { nil: undefined })
        }),
        async (userData) => {
          const response = await request(app)
            .post('/api/platform-admin/users')
            .set('Authorization', `Bearer ${adminToken}`)
            .send(userData);

          if (!userData.permissions || userData.permissions.length === 0) {
            // Should fail validation for COMPANY_ADMIN without permissions
            expect(response.status).toBe(400);
            expect(response.body.success).toBe(false);
            expect(response.body.error).toContain('Permissions array is required for Company Admin role');
          } else {
            // Should succeed with valid permissions
            if (response.status === 201) {
              expect(response.body.success).toBe(true);
              expect(response.body.data.role).toBe('COMPANY_ADMIN');
              
              // Clean up created user
              await prisma.user.delete({
                where: { id: response.body.data.id }
              });
            }
          }
        }
      ),
      { numRuns: 10 }
    );
  });

  it.skip('should handle DRIVER role with optional driver-specific fields', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.record({
          email: fc.emailAddress(),
          firstName: fc.string({ minLength: 1, maxLength: 50 }),
          lastName: fc.string({ minLength: 1, maxLength: 50 }),
          phone: fc.option(fc.string({ minLength: 8, maxLength: 15 }), { nil: undefined }),
          role: fc.constant('DRIVER'),
          companyId: fc.constant(testCompany.id),
          driverLicense: fc.option(fc.string({ minLength: 5, maxLength: 20 }), { nil: undefined }),
          vehicleTypes: fc.option(fc.array(fc.constantFrom('CAR', 'VAN', 'TRUCK')), { nil: undefined })
        }),
        async (userData) => {
          const response = await request(app)
            .post('/api/platform-admin/users')
            .set('Authorization', `Bearer ${adminToken}`)
            .send(userData);

          // Driver role should be accepted regardless of driver-specific fields
          // (backend maps DRIVER to COMPANY_USER role)
          if (response.status === 201) {
            expect(response.body.success).toBe(true);
            expect(response.body.data.role).toBe('DRIVER');
            
            // Clean up created user
            await prisma.user.delete({
              where: { id: response.body.data.id }
            });
          } else if (response.status === 409) {
            // Email already exists - this is expected in property testing
            expect(response.body.error).toContain('Email already exists');
          }
        }
      ),
      { numRuns: 10 }
    );
  });

  it.skip('should accept CUSTOMER role with minimal fields', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.record({
          email: fc.emailAddress(),
          firstName: fc.string({ minLength: 1, maxLength: 50 }),
          lastName: fc.string({ minLength: 1, maxLength: 50 }),
          phone: fc.option(fc.string({ minLength: 8, maxLength: 15 }), { nil: undefined }),
          role: fc.constant('CUSTOMER'),
          companyId: fc.constant(testCompany.id)
        }),
        async (userData) => {
          const response = await request(app)
            .post('/api/platform-admin/users')
            .set('Authorization', `Bearer ${adminToken}`)
            .send(userData);

          // Customer role should be accepted with minimal fields
          if (response.status === 201) {
            expect(response.body.success).toBe(true);
            expect(response.body.data.role).toBe('CUSTOMER');
            
            // Clean up created user
            await prisma.user.delete({
              where: { id: response.body.data.id }
            });
          } else if (response.status === 409) {
            // Email already exists - this is expected in property testing
            expect(response.body.error).toContain('Email already exists');
          }
        }
      ),
      { numRuns: 10 }
    );
  });

  it.skip('should reject invalid roles', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.record({
          email: fc.emailAddress(),
          firstName: fc.string({ minLength: 1, maxLength: 50 }),
          lastName: fc.string({ minLength: 1, maxLength: 50 }),
          role: fc.string().filter(role => !['CUSTOMER', 'DRIVER', 'COMPANY_ADMIN'].includes(role)),
          companyId: fc.constant(testCompany.id)
        }),
        async (userData) => {
          const response = await request(app)
            .post('/api/platform-admin/users')
            .set('Authorization', `Bearer ${adminToken}`)
            .send(userData);

          // Should reject invalid roles
          expect(response.status).toBe(400);
          expect(response.body.success).toBe(false);
          expect(response.body.error).toContain('Invalid role');
        }
      ),
      { numRuns: 10 }
    );
  });

  it.skip('should validate role-specific field combinations', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.oneof(
          // COMPANY_ADMIN with permissions
          fc.record({
            email: fc.emailAddress(),
            firstName: fc.string({ minLength: 1, maxLength: 50 }),
            lastName: fc.string({ minLength: 1, maxLength: 50 }),
            role: fc.constant('COMPANY_ADMIN'),
            companyId: fc.constant(testCompany.id),
            permissions: fc.array(fc.constantFrom('MANAGE_DRIVERS', 'VIEW_BOOKINGS'), { minLength: 1 })
          }),
          // DRIVER with driver fields
          fc.record({
            email: fc.emailAddress(),
            firstName: fc.string({ minLength: 1, maxLength: 50 }),
            lastName: fc.string({ minLength: 1, maxLength: 50 }),
            role: fc.constant('DRIVER'),
            companyId: fc.constant(testCompany.id),
            driverLicense: fc.string({ minLength: 5, maxLength: 20 }),
            vehicleTypes: fc.array(fc.constantFrom('CAR', 'VAN'))
          }),
          // CUSTOMER with basic fields
          fc.record({
            email: fc.emailAddress(),
            firstName: fc.string({ minLength: 1, maxLength: 50 }),
            lastName: fc.string({ minLength: 1, maxLength: 50 }),
            role: fc.constant('CUSTOMER'),
            companyId: fc.constant(testCompany.id)
          })
        ),
        async (userData) => {
          const response = await request(app)
            .post('/api/platform-admin/users')
            .set('Authorization', `Bearer ${adminToken}`)
            .send(userData);

          // All valid role-field combinations should succeed
          if (response.status === 201) {
            expect(response.body.success).toBe(true);
            expect(response.body.data.role).toBe(userData.role);
            expect(response.body.data.companyId).toBe(testCompany.id);
            
            // Clean up created user
            await prisma.user.delete({
              where: { id: response.body.data.id }
            });
          } else if (response.status === 409) {
            // Email already exists - this is expected in property testing
            expect(response.body.error).toContain('Email already exists');
          } else {
            // Any other error should not happen with valid data
            console.error('Unexpected error:', response.body);
            expect(response.status).toBe(201);
          }
        }
      ),
      { numRuns: 10 }
    );
  });
});