-- Grant all privileges to omaraltaf user
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO omaraltaf;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO omaraltaf;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO omaraltaf;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO omaraltaf;
